
server:
  port: ${user_port}
spring:
  datasource:
    username: ${db_postgre_username}
    password: ${db_postgre_password}
    url: ${db_postgre_url_userdb}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


myapplication:
  feign:
    auth: http://localhost:8090/api/v1/auth
    post: http://localhost:8092/api/v1/post