server:
  port: 8086
spring:
  datasource:
    username: ${db_postgre_username}
    password: ${db_postgre_password}
    url: ${db_postgre_url}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
myapplication:
  feign:
    user:
      profile: http://localhost:8091/api/v1/user
      follow : http://localhost:8091/api/v1/follow
    post: http://localhost:8092/api/v1/post

